public with sharing class AccountTerrRunRequest {

    public class accFields {    
        public Boolean allOrNone;
      
        public List<fieldValues> records;
       
    }

    public class fieldValues {
        public arrtributeValues  zattributes;   
   
        public string Id;
        public Decimal TerrRun;
            
    }

    public class arrtributeValues {

        public String type;
    }
}