/**
* @author Dilowar Hussain
* @date 2022
*
* @group N/A
* @group-content N/A
*
* @description Jira Item Trigger leveraging the Trigger Handler framework
* Note : The dynamic trigger handler e.g. DynamicValidationTriggerHandler,
* DynamicBusinessRuleActionTriggerHandler require a trigger to be created.
* so even though this class might look empty, it is still required if there DynamicBusinessRuleAction is used
*/
public with sharing class AddSerialAccTriggerHandler extends TriggerHandler{
    
}