/**
* @author Salesforce Services
* @date 10/28/2019
*
* @group N/A
* @group-content N/A
*
* @description AgentWork Trigger leveraging the Trigger Handler framework
* Note : The dynamic trigger handler e.g. DynamicValidationTriggerHandler and 
* DynamicBusinessRuleActionTriggerHandler require a trigger to be created.
* so even though this class might look empty, it is still required if there DynamicBusinessRuleAction is used
*/

public with sharing class AgentWorkTriggerHandler extends TriggerHandler{

}