/**
* Trigger handler for SBQQ__Subscription__c Object
*
* @Author Rahul Migwani
* @Date 2022/05/18
* @group Trigger
*
* Note : The dynamic trigger handler e.g. DynamicValidationTriggerHandler,
* DynamicBusinessRuleActionTriggerHandler require a trigger to be created.
* so even though this class might look empty, it is still required if there DynamicBusinessRuleAction is used
*/

public with sharing class AssetTriggerHandler extends TriggerHandler {


}