/**
* Trigger handler for Address Object
*
* @Author Abi
* @Date 2019/04/11
* @group Trigger
*
* Note : The dynamic trigger handler e.g. DynamicValidationTriggerHandler,
* DynamicBusinessRuleActionTriggerHandler require a trigger to be created.
* so even though this class might look empty, it is still required if there DynamicBusinessRuleAction is used
*/

public with sharing class AssignedSerialTriggerHandler extends TriggerHandler {

}