/**
* Trigger handler for Compliance log Object
*
* @Author Ivan Yeung
* @Date 2018/12/18
* @group Trigger
*
* Note : The dynamic trigger handler e.g. DynamicValidationTriggerHandler,
* DynamicBusinessRuleActionTriggerHandler require a trigger to be created.
* so even though this class might look empty, it is still required if there DynamicBusinessRuleAction is used
*/

public with sharing class ComplianceLogTriggerHandler extends TriggerHandler {


}