/**
* @author        Ivan Yeung/salesforce services
* @date          2019-02-15
* @description   Unit Test class for AgreementViewControllerTest
* @group         Test
*
*/
@isTest
public with sharing class CudaCommunityThemeLayoutControllerTest {

    @isTest static void unitTest() {

        CudaCommunityThemeLayoutController controller = new CudaCommunityThemeLayoutController();
    String url = CudaCommunityThemeLayoutController.getCommunityBaseUrl();

    }

}