/**
 * As part of 10770 this class has been commented as the source class is not used anymore
 */
@isTest public class CustomHybridPrechatControllerTest
{
    // @isTest
    // static void test_CreateCase(){

    //     CustomHybridPrechatController.createCase('John', 'Smith', 'john.smith@barracuda.com', 'Test', '00001', '22828', 'EXT-LIVE-11111');

    // }

    // @isTest
    // static void test_CreateLeadWithOwner(){

    //     CustomHybridPrechatController.createLeadWithOwner('John', 'Smith', 'john.smith@barracuda.com', 'Test', 'test co', 'EXT-LIVE-11222', null);

    // }


    // @isTest
    // static void test_CreateLeadWithOwner2(){


    //     // by pass business action ,
    //     TriggerHandler.bypass('DynamicBusinessRuleActionTriggerHandler'); // among other things, keep the contact status as active
    //     List <Lead> l = TestDataFactory.postMQLLeads;
    //     TriggerHandler.clearAllBypasses();

    //     // need barracuda domain: barracuda.com, barracudamsp.
    //     CustomHybridPrechatController.createLeadWithOwner(l[0].FirstName, l[0].LastName, l[0].email + '.barracuda.com', 'Test', 'test co', 'EXT-LIVE-11333', null);

    // }

}