/**
* Trigger handler for Address Object
*
* @Author Ivan Yeung
* @Date 2091/06/15
* @group Trigger
*
* Note : The dynamic trigger handler e.g. DynamicValidationTriggerHandler,
* DynamicBusinessRuleActionTriggerHandler require a trigger to be created.
* so even though this class might look empty, it is still required if there DynamicBusinessRuleAction is used
*/

public with sharing class IntegrationSnapshotTriggerHandler extends TriggerHandler {

    


}