/**
* Trigger handler for Serial Object
*
* @Author Yuli
* @Date 2019/10/11
* @group Trigger
*
* Note : The dynamic trigger handler e.g. DynamicValidationTriggerHandler,
* DynamicBusinessRuleActionTriggerHandler require a trigger to be created.
* so even though this class might look empty, it is still required if there DynamicBusinessRuleAction is used
*/
public with sharing class SerialTriggerHandler extends TriggerHandler {

}