name: Salesforce CI/CD to Sandbox

on:
  push:
    branches:
      - staging-neocol-2024
      - dev/Integration

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Salesforce CLI and Delta Plugin
      run: |
        npm install @salesforce/cli --global
        sfdx plugins --core  # Verify that sgd plugin is installed
        sf plugins install sfdx-git-delta

    - name: Set Environment Variables # Storing authentication and target org as environment variables.
      run: |
        if [[ "${GITHUB_REF}" == "refs/heads/staging-neocol-2024" && "${{ github.repository }}" == 'Ignacio-Farias-Neocol/sfdc' ]]; then
          echo "SFDX_AUTH_URL=${{ secrets.SFDX_SANDBOX_AUTH_URL }}" >> $GITHUB_ENV         
          echo "TARGET_ORG=CudaStaging" >> $GITHUB_ENV 
        elif [[ "${GITHUB_REF}" == "refs/heads/dev/Integration" && "${{ github.repository }}" == 'Ignacio-Farias-Neocol/sfdc' ]]; then
          echo "SFDX_AUTH_URL=${{ secrets.SFDX_DEVINTG_AUTH }}" >> $GITHUB_ENV         
          echo "TARGET_ORG=CudadevIntg" >> $GITHUB_ENV 
        fi

    - name: Authenticate to Sandbox # Using the stored environment variable to authenticate.
      env:
        SFDX_AUTH_URL: ${{ env.SFDX_AUTH_URL }}
      run: |
        echo $SFDX_AUTH_URL > sfdx_auth_url.txt
        sfdx auth:sfdxurl:store -f sfdx_auth_url.txt --alias $TARGET_ORG

    - name: Create delta package using sgd
      run: |
        sf sgd source delta --to "HEAD" --from "HEAD~1" --output "."
        ls -al delta  # Verifying the delta directory

    - name: Deploy delta package to Salesforce Sandbox # Deploy only the delta changes.
      run: |
        sfdx force:source:deploy -x package/package.xml
